### ISSUE TITLE
No *Feeds

### ISSUE THREAD

**Issue by Andonome** [AN3223/sakra#1]
> ./sakra: 137: ./sakra: cannot open /home/ghost/.sakra/*.feeds: No such file

I got a ~/.sakra/things file, but now there's *.feeds here too.

Shells tried: bash, dash.

**Comment by AN3223** [comment]
The feeds file needs to end with the extension ".feeds" so rename
~/.sakra/things to ~/.sakra/things.feeds and see how that works.

**Comment by AN3223** [comment]
Commit 12fd39d1033d60ffe86b8dcec6b1b0ed4388c926 should provide a more
descriptive error for this situation.

**Comment by AN3223** [comment]
Closing now
